name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: testWriteResult1
      id: testwriteresult1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testWriteResult1
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ProgE3Test.testWriteResult1"
        timeout: 10
        max-score: 3
    - name: testWriteResult2
      id: testwriteresult2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testWriteResult2
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ProgE3Test.testWriteResult2"
        timeout: 10
        max-score: 5
    - name: testCatchException
      id: testcatchexception
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testCatchException
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ProgE3Test.testCatchException"
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTWRITERESULT1_RESULTS: "${{steps.testwriteresult1.outputs.result}}"
        TESTWRITERESULT2_RESULTS: "${{steps.testwriteresult2.outputs.result}}"
        TESTCATCHEXCEPTION_RESULTS: "${{steps.testcatchexception.outputs.result}}"
      with:
        runners: testwriteresult1,testwriteresult2,testcatchexception
